version: 2.1
# Orb Dependencies
orbs:
  gcloud: circleci/gcp-cli@1.0.6
  gcr: circleci/gcp-gcr@0.0.2
  go: circleci/go@1.3.0
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - go/load-cache
      - go/mod-download
      - go/save-cache

      # Run tests
      - run:
          name: Run tests
          command: |
            go vet ./...
            go test ./...

  dev:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - go/load-cache
      - go/mod-download
      - go/save-cache

      # Deploy app dev
      - run:
          name: Deploying app dev
          command: |
            if [[ $CIRCLE_BRANCH == production ]] ; then
              BUILD_NUM=<< pipeline.number >>
              echo "Create .env file"
              sh ./deploy/create_env_file.sh
              echo "Deploying app dev"
              sudo apt-get install google-cloud-sdk-app-engine-go
              gcloud app deploy --project $GOOGLE_PROJECT_ID -q
            else echo "Not executing on a branch other than master"
            fi

  send-approval-link:
    docker:
      - image: circleci/golang:1.14
    steps:
      - slack/notify:
          channel: $SLACK_CHANNEL_ID
          message: |
            Please check and approve Job to deploy.
            https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
          webhook: $SLACK_WEBHOOK

  staging:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - go/load-cache
      - go/mod-download
      - go/save-cache

        # Deploy app staging
      - run:
          name: Deploying app staging (Narodny opros)
          command: |
            if [[ $CIRCLE_BRANCH == production ]] ; then
              BUILD_NUM=<< pipeline.number >>
              echo "Create .env file"
              sh ./deploy/create_env_file_stag.sh
              echo "Deploying app staging (Narodny opros)"
              sudo apt-get install google-cloud-sdk-app-engine-go
              gcloud app deploy --project $GOOGLE_PROJECT_ID staging.yml -q
            else echo "Not executing on a branch other than master"
            fi

# TODO the first step is dev(Free elections) - > approval - > staging(Narodny opros) - > approval - >  prod
workflows:
  version: 2.1
  main:
    jobs:
      - build:
          context: Deployment
      - dev:
          context: Deployment
          requires:
            - build
      - send-approval-link:
          context: Deployment
          filters:
            branches:
              only: master
          requires:
            - dev
      - hold:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - send-approval-link
            - dev
      - staging:
          context: Deployment
          requires:
            - build
            - hold
#      - prod:
#          context: Deployment
#          requires:
#            - hold