#!/bin/bash
# Create an .env file for staging
echo VIBER_KEY=$VIBER_KEY_STAG >> .env
echo CALLBACK_URL=$CALLBACK_URL_STAG >> .env
echo DB_CONNECTION=$DB_CONNECTION_STAG >> .env
echo DATASTORE_USER_ANSWER_LOG_TABLE=$DATASTORE_USER_ANSWER_LOG_TABLE >>.env
echo DATASTORE_USERS_TABLE=$DATASTORE_USERS_TABLE >>.env
